In [2]:
import pandas as pd
df=pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# df.columns 컬럼리스트
df.columns
# df[컬럼이름]
df['이름']
# df[[컬럼이름, 컬럼이름]]:2개 이상일 때 []리스트 형태로 
# df[['이름','수학']]
# # df['이름':'과학']:컬럼 슬라이싱 안됨
# df[df.columns[0:4]] #컬럼을 사용해서 슬라이싱 적용 가능
# df.loc[:,'이름':'수학'] #loc를 사용해서 슬라이싱 가능

# df.columns[-1] #마지막 컬럼 이름
# df[df.columns[-1]] #마지막 컬럼출력
# df[df.columns[[0,3,-1]]]

# 행 슬라이싱
# loc는 끝포함/ iloc는 끝 제외
df[0:3] #index에 해당되는 3개 출력, 주소가 0,1,2의 rows가 출력
# df.iloc[0:3] #index에 해당되는 3개 출력,행 주소가 0,1,2의 rows가 출력
df.loc['1번':'3번'] #index 이름이 1번에서 3번까지의 행(rows)가 출력

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    강나래  구로고  197  90  85  100  95  85      Python
2번    강태원  구로고  184  40  35   50  55  25        Java
3번    강호림  구로고  168  80  75   70  80  75  Javascript

In [ ]:
# loc 출력 - index출력
# loc = 이름(label)으로 찾기
# loc[[index명],[columns명]]/ loc[행 선택, 열 선택]
# loc의 슬라이싱은 끝값을 포함한다
df.loc['1번']
df.loc[['1번','2번']]
df.loc['1번':'5번']
df.loc['1번','이름':'수학'] #1번 index의 이름~수학까지의 값 : 슬라이싱 가능
df.loc['1번':'5번','이름':'수학'] #1번~5번 index의 이름~수학까지의 값 : 슬라이싱 가능
df.loc[['1번','5번'],'이름':'수학'] #1번,5번 index의 이름~수학까지의 값 : 슬라이싱 가능

       이름   학교    키  국어  영어   수학
지원번호
1번    강나래  신림고  197  90  85  100
5번    김재욱  신림고  188  15  20   10

In [ ]:
#iloc 출력-리스트번호로 출력 (행위치번호)
# iloc = 위치(position)로 찾기
df.iloc[0]
df.iloc[0:4] #index주소값이 0~3까지의 행이 출력
df.iloc[[0,1,4]] #index주소값이 0,1,4 인 행 출력
df.iloc[0:4,1:5] #index주소값이 0~3인 행 중에 컬럼 주소값이 1~4까지 값만 출력
df.iloc[[1,4],1:5] #index주소값이 1,4 인 행 중에 컬럼 주소값이 1~4까지 값만 출력

이름         강나래
학교         구로고
키          197
국어          90
영어          85
수학         100
과학          95
사회          85
SW특기    Python
Name: 1번, dtype: object

In [ ]:
# 조건 :True, False 형태로 리턴
# df['키']>=185

# True인 행만 값 출력
# 키가 185이상인 학생의 행만 선택->그중 키 컬럼만 출력 ->키가 185 이상인 행을 찾고, 그 학생들의 키만 출력한다.
df[df['키']>=185]['키']

지원번호
1번    197
4번    187
5번    188
6번    202
7번    188
8번    190
Name: 키, dtype: int64

In [ ]:
# 국어가 80점 이상인 행 전체를 가져온다.
df[df['국어']>=80]

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85      Python
3번    강호림   신림고  168   80   75   70  80  75  Javascript
6번    박동현  디지털고  202   80  100   95  85  80           C
8번    승근열  디지털고  190  100   85   90  95  95          C#

In [ ]:
df[df['키']>190]['학교':'과학'] #이거는 잘못된 문법. 안으로 들어가야함

Empty DataFrame
Columns: [이름, 학교, 키, 국어, 영어, 수학, 과학, 사회, SW특기]
Index: []

In [ ]:
# df.loc[(index)row, column]
# 키가 190보다 큰 행 중에서 학교부터 과학까지의 컬럼을 가져온다
df.loc[df['키']>190,'학교':'과학']

        학교    키  국어   영어   수학  과학
지원번호
1번     신림고  197  90   85  100  95
6번    디지털고  202  80  100   95  85

In [ ]:
# 키 185보다 크고 학교가 디지털고 인 행을 가져온다 (2개 조건 충족인 행만)
df.loc[(df['키']>185) & (df['학교']=='디지털고')]
# 키 185보다 크거나 학교가 디지털고 인 행을 가져온다 (1개 이상 조건 충족인 행)
df.loc[(df['국어']>85) | (df['수학']>90)]

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   신림고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#