In [40]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df=pd.DataFrame(data)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화      8 non-null      str
 1   개봉 연도   8 non-null      int64
 2   관객 수    8 non-null      int64
 3   평점      8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 388.0 bytes

In [41]:
# 관객수 상위 5개만 출력하시오
# df.nlargest(5,'관객 수')


# # 관객수 1,761 /천단위 출력 '{:,d}'.format() 함수사용
# {:,}.format은 숫자에 천단위 콤마를 넣는 용도
def cal_change(x):
    return f'{x:,}'
df['관객 수']=df['관객 수'].apply(cal_change)

# 숫자에 천 단위 ,를 넣고 문자열로 바꾸는 것
# df['관객 수']=df['관객 수'].map('{:,}'.format)


# 관객수 1761만명/ 만명 추가
# 천단위, 가 없으면 int라서 .astype(str)를 붙여야 함
# df['관객 수']=df['관객 수'].astype(str)

df['관객 수']=df['관객 수']+'만명'
df

          영화  개봉 연도     관객 수    평점
0         명량   2014  1,761만명  8.88
1       극한직업   2019  1,626만명  9.20
2  신과함께-죄와 벌   2017  1,441만명  8.73
3       국제시장   2014  1,426만명  9.16
4         괴물   2006  1,301만명  8.62
5        도둑들   2012  1,298만명  7.64
6    7번방의 선물   2013  1,281만명  8.83
7         암살   2015  1,270만명  9.10

In [39]:
# # 1. 관객수 1,761 /천단위 출력 '{:,d}'.format() 함수사용
# # {:,}.format은 숫자에 천단위 콤마를 넣는 용도
# def cal_change(x):
#     return f'{x:,}'
# df['관객 수']=df['관객 수'].apply(cal_change)


# # 2.lambda함수 적용(함수를 1줄로 작성)
# df['관객 수']=df['관객 수'].apply(lambda x:f'{x:,}')


# # 3. map를 이용하여숫자에 천 단위 ,를 넣고 문자열로 바꾸는 것
# # df['관객 수']=df['관객 수'].map('{:,}'.format)

In [67]:
import pandas as pd
data = {
    '영화' : ['명량', '극한직업', '신과함께-죄와 벌', '국제시장', '괴물', '도둑들', '7번방의 선물', '암살'],
    '개봉 연도' : [2014, 2019, 2017, 2014, 2006, 2012, 2013, 2015],
    '관객 수' : [1761, 1626, 1441, 1426, 1301, 1298, 1281, 1270], # (단위 : 만 명)
    '평점' : [8.88, 9.20, 8.73, 9.16, 8.62, 7.64, 8.83, 9.10]
}
df=pd.DataFrame(data)

In [53]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화      8 non-null      str
 1   개봉 연도   8 non-null      int64
 2   관객 수    8 non-null      int64
 3   평점      8 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 388.0 bytes

In [69]:
#  개봉연도 내림차순, 오름차순 으로 출력하시오.
# 개봉 연도 컬럼만 보여줌
# df['개봉 연도'].sort_values(ascending=False)
# df['개봉 연도'].sort_values()

# 전체 정보까지 같이
# df.sort_values('개봉 연도')
# df.sort_values('개봉 연도', ascending=False)

#  평점이 9점이상만 출력하시오.
# df.loc[df['평점']>9]

filt=df['평점']>=9
df[filt]


#  평점 컬럼 내용에 8.88점 글자를 넣어서 출력하시오.
# df['평점']=df['평점'].astype(str)+'점
# df

# 평점중에 평점 평균이상인 row만 출력하시오.
# df['평점'].mean() #8.77
# df.loc[df['평점']>=8.77]

filt=df['평점']>=df['평점'].mean()
df[filt]

# 2015년 이후에 개봉한 영화를 출력하시오.
# df.loc[df['개봉 연도']>2015]

        영화  개봉 연도  관객 수    평점
0       명량   2014  1761  8.88
1     극한직업   2019  1626  9.20
3     국제시장   2014  1426  9.16
6  7번방의 선물   2013  1281  8.83
7       암살   2015  1270  9.10