In [42]:
import pandas as pd
df=pd.read_excel('file/score.xlsx', index_col='지원번호')

In [37]:
# 합계, 평균,결과 컬럼을 추가
df['합계']=df['국어']+df['영어']+df['수학']
df['평균']=df['합계']/3
# # 실제 값을 소수점 2자리로 반올림
# df['평균'] = (df['합계'] / 3).round(2)
df['결과']='불합격'
df
# 결과 :평균점수가 70점 이상은 합격, 제외는 불합격으로 출력
df.loc[df['평균']>=70,'결과']='합격'
# df

In [27]:
cols=list(df.columns)
cols

['이름', '학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계', '평균', '결과']

In [ ]:
# 원하는 컬럼만 출력
# df2=df[['이름','평균','결과']]
# df2


# 컬럼 순서 변경 
# 1. 컬럼 명을 다 입력하여 변경하기
# df[['이름','평균','결과','학교', '학년', '키', '국어', '영어', '수학', 'SW특기', '합계']]

# 2. 리스트 타입으로 변경하여 조합하기
# 리스트 타입을 때만 더하기가 가능.
# a_list=[1,2,3]
# b_list=[4,5,6]
# c=a_list+b_list
# c

# 그래서 리스트타입으로 변경해서
# cols=list(df.columns)
# cols리스트 순서를 변경
# cols[-2:] #평균, 결과 컬럼, list타입
# cols[0] #이름 , str타입-list타입으로 변경하려면 []로 묶어줘야 함
# cols[1:-2] #학교~합계, list타입
# cols=[cols[0]]+cols[-2:]+cols[1:-2]

df=df[cols]

In [22]:
# 그룹으로 개수 확인 가능 
df.value_counts('결과')

결과
불합격    72
합격     28
Name: count, dtype: int64

In [35]:
# 컬럼 수정-replace, 존재하는 컬럼에 값을 입력하면 수정됨
# 컬럼 추가 -없는 컬럼에 값을 입력하면 추가됨
# 컬럼 삭제-drop:여러개 삭제 가능, inplace=True적용

# index

In [64]:
import pandas as pd
df=pd.read_excel('file/score.xlsx', index_col='지원번호')

In [55]:
# row:index수정, 추가, 삭제
# index 삭제-조건문을 사용하여 삭제

# index값으로 삭제
# df.drop(index=['1번','2번'],inplace=True)


# 조건을 이용한 index삭제
# 수학점수가 80점 미만학생 삭제
filt=df['수학']<80
# df2=df[~filt]
# df2 #수학점수 80점 이상 학생만 출력
# df[filt].count() 몇명인지 알 수 있음

df.drop(index=df[filt].index,inplace=True)
df

       이름    학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    강나래   구로고  197   90   85  100  95  85  Python
6번    박동현  디지털고  202   80  100   95  85  80       C
8번    승근열  디지털고  190  100   85   90  95  95      C#

In [72]:
df.columns
# 국어,영어,수학,과학,사회,합계 컬럼을 추가하고 합계 점수가 350점 이상만 출력하시오

# 컬럼 추가
df['합계']=df['국어']+df['영어']+df['수학']+df['사회']+df['과학']
# 350점 이상만 출력:원본은 그대로 조회
filt=df['합계']>=350
df[filt]
# 350점 미만 삭제 후 출력:원본에서도 삭제
df.drop(index=df[~filt].index,inplace=True)

In [71]:
# index추가:loc[]이용, 컬럼 개수만큼 입력
df.loc['9번']=['홍길동','구로고',190,90,80,70,60,50,'Python']

# 특정 위치 부분값을 추가 또는 수정:index, columns 지정하여 값 입력
df.loc['4번','SW특기']='C'

# 학교, SW특기 컬럼에 값 부분 수정
df.loc['4번',['학교','SW특기']]=['디지털고','Python']
# 
df.loc['5번',['학교','사회','SW특기']]=['디지털고',50,'Java']

In [ ]:
# 컬럼 이름 변경:전체수정
# df.columns=[변경할 이름]
# df2=df[['이름','국어','영어']]
# df2.columns=['name','kor','eng']

# 부분 컬럼 이름 변경
df.rename(columns={'이름':'name','국어':'kor','영어':'eng'},inplace=True)
df.rename(columns={'학교':'school'},inplace=True)
df

     name school    키  kor  eng   수학  과학  사회        SW특기   합계
지원번호
1번    강나래    구로고  197   90   85  100  95  85      Python  455
3번    강호림    구로고  168   80   75   70  80  75  Javascript  380
6번    박동현   디지털고  202   80  100   95  85  80           C  440
8번    승근열   디지털고  190  100   85   90  95  95          C#  465
9번    홍길동    구로고  190   90   80   70  60  50      Python  350