In [2]:
import pandas as pd
df=pd.read_excel('file/score.xlsx',index_col='지원번호')

In [ ]:
# 데이터 수정
# 권장사항
# replace():값 자체가 구로고인 경우 변경
# df['학교'].replace({'구로고':'신림고','디저털고':'사거리고'},inplace=True) 보다는 아래 코드를 권장
# df['학교']=df['학교'].replace({'구로고':'신림고','디저털고':'사거리고'}) # 수정 경과를 df['학교']에 다시 저장

# str.replace():문자열 안에 구로고가 포함되어 있으면 변경
# df['학교'].str.replace('구로고','신림고')

# 데이터 수정

In [45]:
# df['학교']=df['학교']+'등학교'
# df['학교']=df['학교'].str.replace('고','고등학교')
# df['학교']=df['학교'].str.replace('구로고','포켓몬고')
# df['SW특기']=df['SW특기'].str.lower()
# df['SW특기']=df['SW특기'].str.upper()
df['SW특기']=df['SW특기'].str.capitalize()

# 데이터 추가
* 없는 컬럼값을 입력하면 추가가 됨

In [3]:
df=pd.read_excel('file/score.xlsx',index_col='지원번호')

In [4]:
df['합계']=df['국어']+df['영어']+df['수학']+df['과학']+df['사회']

In [5]:
df['결과']='불합격'

In [10]:
# 350점 이상을 합격으로 변경
# df[df['합계']>=350]['결과']='합격' # df[컬럼] 형태 안됨

# 컬럼 전체를 수정할 때 df['컬럼']
# df[df['합계']>=350]['결과']='합격' # 수정안됨. 문법 틀림.
# df['국어']=df['국어']+10

# 컬럼의 부분적인 값을 넣을 때는 loc,iloc를 사용
df.loc[df['합계']>=350,'결과']='합격'

In [11]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기   합계   결과
지원번호
1번    강나래   구로고  197  100   85  100  95  85      Python  455   합격
2번    강태원   구로고  184   50   35   50  55  25        Java  205  불합격
3번    강호림   구로고  168   90   75   70  80  75  Javascript  380   합격
4번    김수찬   구로고  187   50   60   70  75  80         NaN  325  불합격
5번    김재욱   구로고  188   25   20   10  35  10         NaN   90  불합격
6번    박동현  디지털고  202   90  100   95  85  80           C  440   합격
7번    박혜정  디지털고  188   65   65   45  40  35      PYTHON  240  불합격
8번    승근열  디지털고  190  110   85   90  95  95          C#  465   합격

In [ ]:
# 컬럼 데이터 삭제:drop
# 합계 컬럼을 삭제
# df.drop(columns=['합계'],inplace=True)
# 합계, 결과 컬럼을 삭제
# df.drop(columns=['합계','결과'],inplace=True)




# index 데이터 삭제 : drop(index)
# df.drop(index='4번',inplace=True)

# 국어 점수가 80점 미만인 학생 삭제
filt=df['국어']<80
df[filt]
# df[filt].index

# 국어 점수가 80점 미만인 행을 삭제
# df.drop(index=df[filt].index,inplace=True)

# 국어 점수가 80점 이상인 행을 삭제
# df.drop(index=df[~filt].index,inplace=True)

# df

       이름    학교    키  국어  영어  수학  과학  사회    SW특기
지원번호
2번    강태원   구로고  184  40  35  50  55  25    Java
4번    김수찬   구로고  187  40  60  70  75  80     NaN
5번    김재욱   구로고  188  15  20  10  35  10     NaN
7번    박혜정  디지털고  188  55  65  45  40  35  PYTHON